language: cpp
sudo: required
dist: trusty

notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: gcc

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - bash <(curl -sS https://nixos.org/nix/install)
  - source $HOME/.nix-profile/etc/profile.d/nix.sh

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - nix-shell --pure

script:
  - echo "It works! Hello from the Nix environment!"
